# permissions for end users to edit servicebindingprojections.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: servicebindingprojection-editor-role
rules:
- apiGroups:
  - internal.service.binding
  resources:
  - servicebindingprojections
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - internal.service.binding
  resources:
  - servicebindingprojections/status
  verbs:
  - get
