name: Build

on:
  push:
    branches:
    - '**'
    - '!dependabot/**'
  pull_request: {}

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.14.x'
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v1.2.1
        with:
          version: v1.30

      - name: Run tests
        run: make test

      - name: Report coverage
        run: bash <(curl -s https://codecov.io/bash)
        env:
          CODECOV_TOKEN: 7e32569a-106c-4d5e-bb0b-e46e199a7ae5
